# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand


# test_that("barra_simple works", {
#   expect_error(data_prueba %>%
#                  barra_simple(gedad, ordenado=FALSE), regexp = NA)
# })
