# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand


# test_that("barra_apilada_1 works", {
#   expect_error(data_prueba %>% 
#   barra_apilada_n(starts_with("q0011_")), regexp = NA)
# })

