# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand


# test_that("barra_apilada_1 works", {
#   expect_error(data_prueba %>% 
#   filter(q0002 %in% 1) %>% 
#   barra_apilada_1(q0003_0002), regexp = NA)
# })

