# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand


# test_that("barra_multiple works", {
#   expect_error(data_prueba %>% 
#   filter(q0002 %in% 1) %>% 
#   barra_multiple(starts_with("q0004_0")), regexp = NA)
# })

