# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

# test_that("barra_simple works", {
# 
# })

# test_that("barra_simple works", {
#   expect_error(base %>% 
#                  grafico_donut(q0021), regexp = NA)
# })
