# Generated by fusen: do not edit by hand


#' Funcion para realizar un grafico de barra apilada de 1 variable.
#' 
#' @param data Base de datos para la funcion
#' @param var Variable para el grafico de barra apilada
#' @importFrom sjlabelled as_label
#' @return Un grafico de barra apilado
#' @examples
#' \dontrun{
#' base %>% 
#'   filter(q0002 %in% 1) %>% 
#'   barra_apilada_1(q0003_0002)
#' }
#' @export

barra_apilada_1<-function(data, var){

  tag<-
    data %>%
    select({{var}}) %>%
    nrow()

  pop<-as.character(lazyeval::lazy(var))[1]

  labels<-
    tibble(
      numero=as.character(unlist(sjlabelled::get_values(data[,pop]), use.names = FALSE)),
      nombres=unlist(sjlabelled::get_labels(data[,pop]), use.names = FALSE),
    ) %>%
    filter(numero!=0)

  colores<-colorRampPalette(c("#F4B183","#FFD966", "#B0D597", "#8FC36B"))

  num_colores<-labels %>%
    nrow()

  tablon<-data %>%

    mutate(
      nombres= sjlabelled::as_label({{var}})
    ) %>%

    #Tabla
    select(numero={{var}}, nombres) %>%
    drop_na(numero) %>%
    filter(numero!=0) %>%
    dplyr::group_by(numero, nombres) %>%
    dplyr::summarize(Freq = n()) %>%
    ungroup() %>%
    dplyr::mutate(prop = round_half_up(Freq/sum(Freq), digits = 2),
                  numero = as.character(numero),
                  nombres = as.character(nombres)) %>%

    full_join(labels) %>%
    mutate(across(where(is.numeric), ~replace_na(.,0))) %>%

    mutate(

      color=colores(num_colores)[as.numeric(numero)],

      total="total"
    ) %>%

    mutate(
      numero2=case_when(
        numero %in% as.character(num_colores-1) ~ as.character(num_colores),
        TRUE ~ numero),


    ) %>%
    group_by(total, numero2) %>%
    mutate(prop2=sum(prop)) %>%
    ungroup()

  tablon %>%

    #GrÃ¡fico
    ggplot(aes(total, prop, label = scales::percent(prop, accuracy = 1) )) +
    geom_col(aes(fill=factor(color, ordered = TRUE, levels = rev(colores(num_colores)) )), position = "fill", width = 0.6) +

    #Etiqueta = 4
    geom_text(aes(y=1.05, label = ifelse((numero == 4 & prop < 0.07) & !(numero == 4 & prop == 0), scales::percent(prop, accuracy = 1), "") ),
              size = 3.5,
              fontface = "bold",
              color = "#002060",
              family="sans") +

    #Etiqueta = 3
    geom_text(aes(y=1.05, label = ifelse((numero == 3 & prop < 0.07) & !(numero == 3 & prop == 0) & (numero == 4 & prop == 0), scales::percent(prop, accuracy = 1), "") ),
              size = 3.5,
              fontface = "bold",
              color = "#002060",
              family="sans") +

    #Etiqueta = 2
    geom_text(aes(y=-0.05, label = ifelse((numero == 2 & prop < 0.07) & !(numero == 2 & prop == 0) & (numero == 1 & prop == 0), scales::percent(prop, accuracy = 1), "") ),
              size = 3.5,
              fontface = "bold",
              color = "#002060",
              family="sans") +

    #Etiqueta = 1
    geom_text(aes(y=-0.05, label = ifelse((numero == 1 & prop < 0.07) & !(numero == 1 & prop == 0), scales::percent(prop, accuracy = 1), "") ),
              size = 3.5,
              fontface = "bold",
              color = "#002060",
              family="sans") +

    #Etiqueta = El resto
    geom_text(aes(label = ifelse(!((numero == 4 & prop < 0.07) |
                                     (numero == 3 & prop < 0.07) & (numero == 4 & prop == 0) |
                                     (numero == 2 & prop < 0.07) & (numero == 1 & prop == 0) |
                                     (numero == 1 & prop < 0.07)) & !(prop == 0), scales::percent(prop, accuracy = 1), "") ),
              position = position_stack(vjust = 0.5),
              size = 3.5,
              fontface = "bold",
              color = "#002060",
              family="sans") +

    #TOP2BOX
    geom_label(aes(y=1.2, label=ifelse(numero2 %in% "4", scales::percent(prop2, accuracy = 1), NA)),
               size = 3.5,
               fontface = "bold",
               color = "#459847",
               family="sans") +
    annotate("text", label="TOP2BOX", x=0, y = 1.2, vjust = -9,
             size = 3.5,
             fontface = "bold",
             color = "#459847",
             family="sans") +

    #eje x y
    scale_y_continuous(labels = scales::percent, limits = c(-0.05, 1.3)) +
    scale_fill_identity(labels=str_wrap(levels(fct_reorder(tablon$nombres, tablon$numero, min)), width = 20), breaks= levels(droplevels(factor(tablon$color, ordered = TRUE, levels = colores(num_colores) ))), guide="legend") +
    coord_flip(clip="off", ylim = c(-0.05, 1.3)) +

    #temas
    theme_pubr() +
    labs(caption = "Elaborado por Pulso PUCP",
         tag = glue("N=",tag)
    ) +
    theme(legend.title = element_blank(),legend.position = "bottom",legend.text = element_text(size = 7, face = "bold",family="sans"),legend.key.height = unit(.2, "cm"),
          plot.caption = element_text(face = "italic",family="sans"),plot.margin = unit(c(0,0,1,0),"cm"),plot.tag = element_text(size = 8, color="grey40"),plot.tag.position = "topright",
          text = element_text(size = 9, color="#002060",family="sans"),
          axis.title = element_blank(),axis.text = element_blank(),axis.ticks = element_blank(),axis.line = element_blank() ) +
    guides(fill = guide_legend(reverse=FALSE,label.position = "bottom"))

}


