# Generated by fusen: do not edit by hand


#' Funcion para realizar un grafico de barras multiple
#' 
#' @param data Base de datos para la funcion
#' @param ... Variables para el grafico de barras multiple
#' @importFrom glue glue
#' @importFrom sjlabelled as_label
#' @return Un grafico de barras mÃºltiple
#' @examples
#' \dontrun{
#' base %>% 
#'   filter(q0002 %in% 1) %>% 
#'   barra_multiple(starts_with("q0004_0"))
#' }
#' @export

barra_multiple<-function(data, ..., subtitulo = "", abierta=nombres, max.limit=1, ultimo=NULL, color = "#B0D597", ext.label=30){

  tag<-
    data %>%
    sjlabelled::as_label() %>%
    select(...) %>% nrow()

  data %>%
    #tabla
    sjlabelled::as_label() %>%
    select(...) %>%
    pivot_longer(everything(), names_to = "pregunta", values_to = "nombres") %>%
    group_by(pregunta, nombres) %>%
    dplyr::summarize(Freq = n()) %>%
    group_by(pregunta) %>%
    dplyr::mutate(pct = round_half_up(Freq/sum(Freq), digits = 2),
                  nombres = as.character(nombres)) %>%
    drop_na(nombres) %>%
    filter(!(nombres %in% "")) %>%
    ungroup() %>%

    #grafico
    ggplot(aes(x =fct_relevel( fct_reorder({{abierta}}, pct, min), ultimo), y = pct) ) +
    geom_bar(stat='identity', fill = color, width = 0.6) +

    #Etiqueta = -10%
    geom_text(aes(label = ifelse(pct < 0.1, scales::percent(pct, accuracy = 1), "") ),
              position = position_dodge(width = .9),
              vjust = 0.2,
              hjust = -0.2,
              size = 3.5,
              fontface = "bold",
              color = "#002060") +

    #Etiqueta = El resto
    geom_text(aes(label = ifelse(pct >= 0.1, scales::percent(pct, accuracy = 1), "") ),
              position = position_stack(vjust = 0.5),
              size = 3.5,
              fontface = "bold",
              color = "#002060") +

    scale_x_discrete(labels = wrap_format(ext.label)) +
    scale_y_continuous(labels=~scales::percent(.x, accuracy = 1), limits = c(0, max.limit)) +
    coord_flip() +
    theme_pubr() +
    labs(subtitle = subtitulo,
         caption = "Elaborado por Pulso PUCP",
         tag = glue("N=",tag) ) +
    theme(plot.caption = element_text(face = "italic"),
          plot.tag = element_text(size = 8, color="grey40"),
          plot.tag.position = "topright",
          plot.subtitle = element_text(face="italic", size = 10),
          plot.title.position = "plot",
          text = element_text(size = 9, color="#002060"),
          axis.title = element_blank(),
          axis.text = element_text(color="#002060"),
          axis.ticks = element_line(color="#002060"),
          axis.line = element_line(color="#002060", size = 0.5) )
}


