# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand


#' Funcion para realizar un grafico de barras simple.
#' 
#' @param data Base de datos para la funcion
#' @param var Variable para el grafico de barras simple
#' @importFrom glue glue
#' @importFrom sjlabelled as_label
#' @return Un grafico de barras simple.
#' @examples
#' 
#' data_prueba %>% 
#'   barra_simple(gedad, ordenado=FALSE)
#' 
#' @export

barra_simple<- function(data, var, ordenado=TRUE, max.limit=1, color = "#B0D597", ultimo=NULL){

  if(isTRUE(ordenado)) {

    tablon<-data %>%
      sjlabelled::as_label() %>%
      count(var = fct_rev(fct_infreq(factor({{var}}))) ) %>%
      mutate(pct = prop.table(n))

  } else {

    tablon<-data %>%
      sjlabelled::as_label() %>%
      count(var = fct_rev(factor({{var}}))) %>%
      mutate(pct = prop.table(n))

  }

  tablon %>%
    #grafico
    ggplot(aes(x = fct_relevel(var, ultimo), y = pct) ) +
    geom_bar(stat='identity', fill = color, width = 0.6) +

    #Etiqueta = -10%
    geom_text(aes(label = ifelse(pct < 0.07, scales::percent(pct, accuracy = 1), "") ),
              position = position_dodge(width = .9),
              vjust = 0.2,
              hjust = -0.2,
              size = 3.5,
              fontface = "bold",
              color = "#002060") +

    #Etiqueta = El resto
    geom_text(aes(label = ifelse(pct >= 0.07, scales::percent(pct, accuracy = 1), "") ),
              position = position_stack(vjust = 0.5),
              size = 3.5,
              fontface = "bold",
              color = "#002060") +

    scale_x_discrete(labels = wrap_format(25)) +
    scale_y_continuous(labels=~scales::percent(.x, accuracy = 1), limits = c(0, max.limit)) +
    coord_flip() +
    theme_pubr() +
    labs(caption = "Elaborado por Pulso PUCP",
         tag = glue("N=",sum(tablon$n))) +
    theme(plot.caption = element_text(face = "italic"),
          plot.tag = element_text(size = 8, color="grey40"),
          plot.tag.position = "topright",
          text = element_text(size = 9, color="#002060"),
          axis.title = element_blank(),
          axis.text = element_text(color="#002060"),
          axis.ticks = element_line(color="#002060"),
          axis.line = element_line(color="#002060", size = 0.5) )

}

