# Generated by fusen: do not edit by hand


#' Funcion para realizar un grafico de barra apilada de n variables.
#' 
#' @param data Base de datos para la funcion
#' @param ... Variables para el grafico de barra apilada
#' @importFrom sjlabelled as_label
#' @return Un grafico de barras apiladas
#' @examples
#' \dontrun{
#' base %>% 
#'   barra_apilada_n(starts_with("q0011_"))
#' }
#' @export

barra_apilada_n<-function(data, ..., ordenado=TRUE){

  tag<-
    data %>%
    select(...) %>%
    nrow()

  nombres_orden<-
    data %>%
    select(...)%>%
    sjlabelled::label_to_colnames() %>%
    names()

  nombres_orden<-ordered(factor(nombres_orden))

  noms<-
    data %>%
    select(...) %>%
    names()

  pop<-as.character(noms)[1]

  labels<-
    tibble(
      pregunta=as.character(unlist(sjlabelled::get_label(data[,pop]), use.names = FALSE)),
      numero=as.character(unlist(sjlabelled::get_values(data[,pop]), use.names = FALSE)),
      nombres=unlist(sjlabelled::get_labels(data[,pop]), use.names = FALSE),
    ) %>%
    filter(numero!=0)

  #Tabla
  tablon<-

    data %>%
    select(...)%>%
    sjlabelled::label_to_colnames() %>%
    pivot_longer(everything(), names_to = "pregunta", values_to = "numero") %>%
    mutate(nombres=sjlabelled::as_label(numero)) %>%
    group_by(pregunta, numero, nombres) %>%
    drop_na(numero) %>%
    filter(numero!=0) %>%
    dplyr::summarize(Freq = n()) %>%
    group_by(pregunta) %>%
    dplyr::mutate(prop = round_half_up(Freq/sum(Freq), digits = 2),
                  numero = as.character(numero),
                  nombres = as.character(nombres)) %>%

    full_join(labels) %>%
    mutate(across(where(is.numeric()), ~replace_na(.,0))) %>%

    ungroup() %>%
    mutate(
      color=case_when(
        numero=="1" ~"#F4B183",
        numero=="2" ~"#FFD966",
        numero=="3" ~"#B0D597",
        numero=="4" ~"#8FC36B",
        TRUE~"#D3D3D3"
      )) %>%

    mutate(
      numero2=case_when(
        numero %in% "3" ~ "4",
        TRUE ~ numero),


    ) %>%
    group_by(pregunta, numero2) %>%
    mutate(prop2=sum(prop)) %>%
    ungroup()


  tablon %>%

    #GrÃ¡fico
    ggplot(aes(x=if(isTRUE(ordenado)){fct_reorder2(pregunta, numero, -prop2)}else{fct_rev(factor(pregunta, levels = nombres_orden))}, y=prop, label = scales::percent(prop, accuracy = 1) )) +
    geom_col(aes(fill=factor(color, ordered = TRUE, levels = c("#8FC36B","#B0D597","#FFD966","#F4B183","#D3D3D3"))), position = "fill", width = 0.6) +

    #Etiqueta = 4
    geom_text(aes(y=1.05, label = ifelse((numero == 4 & prop < 0.06) & !(numero == 4 & prop == 0), scales::percent(prop, accuracy = 1), "") ),
              size = 3.5,
              fontface = "bold",
              color = "#002060",
              family="sans") +

    #Etiqueta = 3
    geom_text(aes(y=1.05, label = ifelse((numero == 3 & prop < 0.06) & !(numero == 3 & prop == 0) & (numero == 4 & prop == 0), scales::percent(prop, accuracy = 1), "") ),
              size = 3.5,
              fontface = "bold",
              color = "#002060",
              family="sans") +

    #Etiqueta = 2
    geom_text(aes(y=-0.05, label = ifelse((numero == 2 & prop < 0.06) & !(numero == 2 & prop == 0) & (numero == 1 & prop == 0), scales::percent(prop, accuracy = 1), "") ),
              size = 3.5,
              fontface = "bold",
              color = "#002060",
              family="sans") +

    #Etiqueta = 1
    geom_text(aes(y=-0.05, label = ifelse((numero == 1 & prop < 0.06) & !(numero == 1 & prop == 0), scales::percent(prop, accuracy = 1), "") ),
              size = 3.5,
              fontface = "bold",
              color = "#002060",
              family="sans") +

    #Etiqueta = El resto
    geom_text(aes(label = ifelse(!((numero == 4 & prop < 0.06) |
                                     (numero == 3 & prop < 0.06) & (numero == 4 & prop == 0) |
                                     (numero == 2 & prop < 0.06) & (numero == 1 & prop == 0) |
                                     (numero == 1 & prop < 0.06)) & !(prop == 0), scales::percent(prop, accuracy = 1), "") ),
              position = position_stack(vjust = 0.5),
              size = 3.5,
              fontface = "bold",
              color = "#002060",
              family="sans") +

    #TOP2BOX
    geom_label(aes(y=1.2, label=ifelse(numero2 %in% "4", scales::percent(prop2, accuracy = 1), NA)),
               size = 3.5,
               fontface = "bold",
               color = "#459847",
               family="sans") +
    annotate("text", label="TOP2BOX", x=as.numeric(count(as.data.frame(unique(tablon$pregunta)))), y = 1.2, vjust = -3,
             size = 3.5,
             fontface = "bold",
             color = "#459847",
             family="sans") +

    #eje x y
    scale_x_discrete(labels = wrap_format(42)) +
    scale_y_continuous(labels = scales::percent, limits = c(-0.05, 1.3)) +
    scale_fill_identity(labels=str_wrap(levels(fct_reorder(tablon$nombres, tablon$numero, min)), width = 20), breaks= levels(droplevels(factor(tablon$color, ordered = TRUE, levels = c("#D3D3D3","#F4B183","#FFD966","#B0D597","#8FC36B")))), guide="legend") +
    coord_flip(clip="off", ylim = c(-0.05, 1.3)) +

    #temas
    theme_pubr() +
    labs(caption = "Elaborado por Pulso PUCP",
         tag=glue("N=", tag)) +
    theme(legend.title = element_blank(),legend.position = "bottom",legend.text = element_text(size = 7, face = "bold",family="sans"),legend.key.height = unit(.2, "cm"),
          plot.caption = element_text(face = "italic",family="sans"),plot.margin = unit(c(0,0,1,0),"cm"),plot.tag = element_text(size = 8, color="grey40"),plot.tag.position = "topright",
          text = element_text(size = 9, color="#002060",family="sans"),
          axis.title = element_blank(),axis.text = element_text(color="#002060"),axis.text.y = element_text(hjust=0.5),axis.text.x = element_blank(),axis.ticks = element_blank(),axis.line = element_blank() ) +
    guides(fill = guide_legend(reverse=FALSE,label.position = "bottom"))

}


