# Generated by fusen: do not edit by hand


#' Funcion para realizar un grafico de barra apilada de n variables.
#' 
#' @param data Base de datos para la funcion
#' @param var Variable para grÃ¡fico donut
#' @importFrom sjlabelled as_label
#' @return Un grafico donut
#' @examples
#' base %>% 
#'   grafico_donut(q0021)
#' @export

grafico_donut<- function(data, var, paleta=1, direction=1) {

  tag<-
    data %>%
    sjlabelled::as_label() %>%
    select({{var}}) %>%
    nrow()

  data %>%
    sjlabelled::as_label() %>%
    group_by({{var}}) %>%
    count() %>%
    rename(count=n) %>%
    ungroup() %>%
    mutate(prop=paste0(round_half_up(count/sum(count), digits = 2)*100, "%"),
           # Compute percentages
           fraction=count/sum(count),
           # Compute the cumulative percentages (top of each rectangle)
           ymax=cumsum(fraction),
           # Compute the bottom of each rectangle
           ymin=c(0, head(ymax, n=-1)),
           # Compute label position
           labelPosition=(ymax + ymin) / 2,
           # Compute a good label
           label=paste0({{var}}, "\n ", prop),
    ) %>%
    # Make the plot
    ggplot(aes(ymax=ymax, ymin=ymin, xmax=4, xmin=1, fill={{var}})) +
    geom_rect() +
    geom_text( x=2.5, aes(y=labelPosition, label=label),
               hjust="middle",
               size = 3.5,
               fontface = "bold",
               color = "#002060",
               family="sans") +
    scale_fill_brewer(type="seq",palette=paleta, direction=direction) +
    coord_polar(theta="y") +
    xlim(c(-1, 4)) +
    theme_void() +
    theme(legend.position = "none",
          text = element_text(size = 9, color="#002060",family="sans"),
          plot.caption = element_text(face = "italic",family="sans"),
          plot.tag = element_text(size = 8, color="grey40"),
          plot.tag.position = "topright") +
    labs(caption = "Elaborado por Pulso PUCP",
         tag = glue("N=",tag))


}


